version: 2.1
orbs:
  node: circleci/node@4.7.0
  jira: circleci/jira@1.3.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    environment:
      MY_VARIABLE: my_value

    steps:
      - checkout
      - run: npm install
      # - run: npm start
      # - run: npm test

workflows:
  build_and_test:
    jobs:
      - build-and-test:
          post-steps:
            - jira/notify