version: 2.1
orbs:
  # node: circleci/node@14
  jira: circleci/jira@1.3.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    environment:
      MY_VARIABLE: my_value

    steps:
      - checkout
      - run: npm install
      # - run: npm start
      # - run: npm test
  deploy:
    docker:
      - image: circleci/node:14
    
    environment:
      FIREBASE_TOKEN: 1//0gQpqrBotiwKRCgYIARAAGBASNwF-L9IritG514rXo2Vq0s2vtga0DtY_UNK17x72l4oDnkA_9lZt3Bwxf8wRIBNQi2Fu8v-a14s
    
    steps: 
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Firebase CLI
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy to firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN


workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
      - deploy: 
          requires:
            - build
