version: 2.1
orbs:
  # node: circleci/node@14
  jira: circleci/jira@1.3.1
jobs:
  build:
    docker:
      - image: circleci/node:10

    environment:
      MY_VARIABLE: my_value

    steps:
      - checkout
      - run: npm install
      # - run: npm start
      # - run: npm test

workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify