version: 2.1
orbs:
  node: circleci/node@4.7.0
  jira: circleci/jira@1.3.1
jobs:
  build:
    executor:
      name: node/default
    # docker:
    #   - image: circleci/node:14

    # environment:
    #   MY_VARIABLE: my_value

    steps:
      - checkout
      - node/install-packages
      - run: npm install
      # - run: npm start
      # - run: npm test

workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify